#!/usr/bin/env python

import os
import sys

here = os.path.dirname(os.path.abspath(__file__))
sys.path.append(here)

virtenv = os.environ['OPENSHIFT_GEAR_DIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except:
    pass

from MoinMoin import log
log.load_config(os.environ['OPENSHIFT_REPO_DIR'] + '/wsgi/logging/logfile')

from MoinMoin import wsgiapp
application = wsgiapp.Application()
